Object.defineProperty(exports, "__esModule", { value: true });
var Rdf = require("../core/Rdf");
var field;
(function (field) {
    var NAMESPACE = 'http://www.metaphacts.com/ontology/fields#';
    var iri = function (s) { return Rdf.iri(NAMESPACE + s); };
    field.Field = iri('Field');
    field.insert_pattern = iri('insertPattern');
    field.select_pattern = iri('selectPattern');
    field.delete_pattern = iri('deletePattern');
    field.ask_pattern = iri('askPattern');
    field.category = iri('category');
    field.domain = iri('domain');
    field.xsd_datatype = iri('xsdDatatype');
    field.range = iri('range');
    field.min_occurs = iri('minOccurs');
    field.max_occurs = iri('maxOccurs');
    field.default_value = iri('defaultValue');
    field.valueset_pattern = iri('valueSetPattern');
    field.autosuggestion_pattern = iri('autosuggestionPattern');
    field.tree_patterns = iri('treePatterns');
    field.testsubject = iri('testSubject');
})(field || (field = {}));
exports.default = field;
