Object.defineProperty(exports, "__esModule", { value: true });
var Rdf = require("../core/Rdf");
var ldp;
(function (ldp) {
    ldp._NAMESPACE = 'http://www.w3.org/ns/ldp#';
    ldp.iri = function (s) { return Rdf.iri(ldp._NAMESPACE + s); };
    ldp.Ascending = ldp.iri('Ascending');
    ldp.BasicContainer = ldp.iri('BasicContainer');
    ldp.constrainedBy = ldp.iri('constrainedBy');
    ldp.Container = ldp.iri('Container');
    ldp.contains = ldp.iri('contains');
    ldp.Descending = ldp.iri('Descending');
    ldp.DirectContainer = ldp.iri('DirectContainer');
    ldp.hasMemberRelation = ldp.iri('hasMemberRelation');
    ldp.IndirectContainer = ldp.iri('IndirectContainer');
    ldp.insertedContentRelation = ldp.iri('insertedContentRelation');
    ldp.isMemberOfRelation = ldp.iri('isMemberOfRelation');
    ldp.member = ldp.iri('member');
    ldp.membershipResource = ldp.iri('membershipResource');
    ldp.MemberSubject = ldp.iri('MemberSubject');
    ldp.NonRDFSource = ldp.iri('NonRDFSource');
    ldp.Page = ldp.iri('Page');
    ldp.pageSequence = ldp.iri('pageSequence');
    ldp.pageSortCollation = ldp.iri('pageSortCollation');
    ldp.pageSortCriteria = ldp.iri('pageSortCriteria');
    ldp.PageSortCriterion = ldp.iri('PageSortCriterion');
    ldp.pageSortOrder = ldp.iri('pageSortOrder');
    ldp.pageSortPredicate = ldp.iri('pageSortPredicate');
    ldp.PreferContainment = ldp.iri('PreferContainment');
    ldp.PreferEmptyContainer = ldp.iri('PreferEmptyContainer');
    ldp.PreferMembership = ldp.iri('PreferMembership');
    ldp.PreferMinimalContainer = ldp.iri('PreferMinimalContainer');
    ldp.RDFSource = ldp.iri('RDFSource');
    ldp.Resource = ldp.iri('Resource');
})(ldp || (ldp = {}));
exports.default = ldp;
