Object.defineProperty(exports, "__esModule", { value: true });
var RDF = require("../core/Rdf");
var platform;
(function (platform) {
    platform._NAMESPACE = 'http://www.metaphacts.com/ontologies/platform#';
    platform.SyntheticJsonDatatype = RDF.iri(platform._NAMESPACE + 'syntheticJson');
    platform.RootContainer = RDF.iri(platform._NAMESPACE + 'rootContainer');
    platform.UserSetContainer = RDF.iri(platform._NAMESPACE + 'userSetContainer');
    platform.SetContainer = RDF.iri(platform._NAMESPACE + 'setContainer');
    platform.ClipboardContainer = RDF.iri(platform._NAMESPACE + 'clipboardContainer');
    platform.VisibilityContainer = RDF.iri(platform._NAMESPACE + 'visibilityContainer');
    platform.FieldDefinitionContainer = RDF.iri(platform._NAMESPACE + 'fieldDefinitionContainer');
    platform.OntodiaDiagramContainer = RDF.iri(platform._NAMESPACE + 'ontodiaDiagramContainer');
    platform.QueryContainer = RDF.iri(platform._NAMESPACE + 'queryContainer');
    platform.QueryTemplateContainer = RDF.iri(platform._NAMESPACE + 'queryTemplateContainer');
    platform.PersistedComponentContainer = RDF.iri(platform._NAMESPACE + 'persistedComponentContainer');
    platform.Set = RDF.iri(platform._NAMESPACE + 'Set');
    platform.containerType = RDF.iri(platform._NAMESPACE + 'containerType');
    platform.setItem = RDF.iri(platform._NAMESPACE + 'setItem');
    platform.setItemIndex = RDF.iri(platform._NAMESPACE + 'setItemIndex');
    platform.clipboardItem = RDF.iri(platform._NAMESPACE + 'clipboardItem');
    platform.visibilityItem = RDF.iri(platform._NAMESPACE + 'visibilityItem');
    platform.visibility = RDF.iri(platform._NAMESPACE + 'visibility');
    platform.publicVisibility = RDF.iri(platform._NAMESPACE + 'visibilityPublic');
    platform.privateVisibility = RDF.iri(platform._NAMESPACE + 'visibilityPrivate');
    platform.sharedVisibility = RDF.iri(platform._NAMESPACE + 'visibilityShared');
    platform.groupVisibility = RDF.iri(platform._NAMESPACE + 'visibilityGroup');
    platform.visibleToGroups = RDF.iri(platform._NAMESPACE + 'visibleToGroups');
    platform.searchState = RDF.iri(platform._NAMESPACE + 'searchState');
    platform.searchResultCategory = RDF.iri(platform._NAMESPACE + 'searchResultCategory');
})(platform || (platform = {}));
exports.default = platform;
