/**
 * ResearchSpace
 * Copyright (C) 2020, © Trustees of the British Museum
 * Copyright (C) 2015-2019, metaphacts GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.researchspace.rest.feature;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.util.concurrent.TimeUnit;

import javax.ws.rs.GET;
import javax.ws.rs.NameBinding;
import javax.ws.rs.POST;

/**
 * Annotations for cach control header injection.
 * 
 * @see CacheControlFeature
 * @author Johannes Trame <jt@metaphacts.com>
 */
public class CacheControl {

    /**
     * Annotation to inject cache control header values into any HTTP response
     * header generated by any {@link GET} or {@link POST} jersey methods. Value
     * must a valid cache control header according to the
     * <a href="https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9" >W3
     * standard</a> i.e. no further validation will be applied when injecting the
     * value into the header.
     */
    @NameBinding
    @Target({ ElementType.METHOD, ElementType.TYPE })
    @Retention(RetentionPolicy.RUNTIME)
    public static @interface Cache {
        /**
         * @return String value that will be used in the "Cache-Control" header field of
         *         the response. Must be a valid value according to the standard i.e.
         *         compare <a href=
         *         "https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9"
         *         >https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9</a>
         */
        String value();
    }

    /**
     * Annotation to inject "Cache-Control" header with static value "max-age=0,
     * no-cache, no-store, must-revalidate" into any HTTP response header generated
     * by any {@link GET} or {@link POST} jersey methods.
     */
    @NameBinding
    @Target({ ElementType.METHOD, ElementType.TYPE })
    @Retention(RetentionPolicy.RUNTIME)
    public static @interface NoCache {
    }

    /**
     * Annotation to inject max-age cache control header value into any HTTP
     * response header generated by any {@link GET} or {@link POST} jersey methods.
     * Similar to {@link Cache} annotation, however, provides more abstraction i.e.
     * the given {@link MaxAgeCache#value()} will be automatically converted to a
     * valid max-age string according to the specified {@link MaxAgeCache#unit()}.
     */
    @NameBinding
    @Target({ ElementType.METHOD, ElementType.TYPE })
    @Retention(RetentionPolicy.RUNTIME)
    public static @interface MaxAgeCache {
        /**
         * @return The time value.
         */
        long time() default 1;

        /**
         * @return The unit of the numerical time value. Default:
         *         {@link TimeUnit#MINUTES}
         */
        TimeUnit unit() default TimeUnit.MINUTES;
    }

}