export const itemSelector: string;
export const dropdown: string;
export const itemHolder: string;
export const focus: string;
export const active: string;
export const open: string;
export const dropdownToggle: string;
export const disabled: string;
export const badge: string;
