export const word: string;
export const separator: string;
export const start: string;
export const domain: string;
export const relation: string;
export const Resource: string;
export const resource: string;
export const Text: string;
export const text: string;
