export const component: string;
export const reorderedItem: string;
export const removableItem: string;
export const multilineEditor: string;
export const removeItemButton: string;
export const storageSelector: string;
export const footer: string;
export const submitControls: string;
export const save: string;
