export const component: string;
export const propertyValuesCell: string;
export const noValue: string;
export const propertyValues: string;
export const propertyValue: string;
export const editValue: string;
export const valuesEditor: string;
export const propertyApps: string;
export const propertyApp: string;
