export const component: string;
export const warning: string;
export const mainPart: string;
export const labeledControl: string;
export const overrideChain: string;
export const overriddenApp: string;
export const effectiveApp: string;
export const overrideArrow: string;
export const selector: string;
